### ISSUE TITLE
After Ruby upgrade, ruby-vips8 is broken

### ISSUE THREAD

**Issue by PaulHowson** [jcupitt/ruby-vips8#3]
Hi John,

More problems with vips unfortunately. This one is hopefully an easy fix.

I upgraded the Ruby version on my Mac to the latest 2.2.3. Previously it was the default Apple-installed version (2.0.0). Had to adjust GEM_PATH to find the old gems. That's working. However, now my very basic Ruby vips test program fails on the first line:

```ruby
require 'vips8'
```

This was of course working previously. The error message is:

```
incompatible library version - /Library/Ruby/Gems/2.0.0/gems/glib2-3.0.7/lib/glib2.bundle
```
The directory `/Library/Ruby/Gems/2.0.0` is the old Ruby 2.0.0 gem directory which I've put into the GEM_PATH. That shouldn't be a problem.

So I did `sudo gem install ruby-vips8` to re-install the gem and libs. That bombs out. Here's a snippet of the output:

```
mps-code $ sudo gem install ruby-vips8
Fetching: pkg-config-1.1.7.gem (100%)
Successfully installed pkg-config-1.1.7
Fetching: glib2-3.0.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed glib2-3.0.8
Fetching: gobject-introspection-3.0.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-vips8:
	ERROR: Failed to build gem native extension.

    /usr/local/opt/ruby/bin/ruby -r ./siteconf20160422-84942-1uoh1tv.rb extconf.rb
```

Then a bit further down after all the 'checking' commands:

```
checking for gobject-introspection-1.0... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.2.3/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/usr/local/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:265:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
```

Probably something obvious. My eyes are glazing over. :)
Any pointers?

Regards, Paul Howson

**Comment by jcupitt** [comment]
Hi @PaulHowson, I've not done a `brew update` for a while, I'll have a go. This is with `brew install ruby` I guess? I'm not sure I've used that.

**Comment by PaulHowson** [comment]
Yes, Ruby installed with `brew install ruby`. It installs Ruby 2.2.3.

There seem to be **two** failures in the above gem install:

The first is:

```
ERROR:  Error installing ruby-vips8:
    ERROR: Failed to build gem native extension.

    /usr/local/opt/ruby/bin/ruby -r ./siteconf20160422-84942-1uoh1tv.rb extconf.rb
```
This message is not particularly illuminating re what's gone wrong.

The second failure is:

```
/usr/local/lib/ruby/gems/2.2.0/gems/pkg-config-1.1.7/lib/pkg-config.rb:265:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
```

Do you know what is the ".pc for libffi" that it's looking for? Looking at the file pkg-config.rb, it's a package manager of some sort and it's looking for this thing in a series of paths.

Hmmm.

**Comment by jcupitt** [comment]
It seems to be working here. I see:

```
john@katamata ~ $ rm -rf /Users/john/packages/gems
john@katamata ~ $ brew install ruby
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.3.0.el_capitan.bottl
Already downloaded: /Library/Caches/Homebrew/ruby-2.3.0.el_capitan.bottle.2.tar.gz
==> Pouring ruby-2.3.0.el_capitan.bottle.2.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/ruby
==> Summary
🍺  /usr/local/Cellar/ruby/2.3.0: 1,260 files, 19.0M
john@katamata ~ $ gem install ruby-vips8
Successfully installed pkg-config-1.1.7
Fetching: glib2-3.0.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed glib2-3.0.8
Fetching: gobject-introspection-3.0.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gobject-introspection-3.0.8
Fetching: ruby-vips8-0.1.0.gem (100%)
Successfully installed ruby-vips8-0.1.0
Parsing documentation for pkg-config-1.1.7
Installing ri documentation for pkg-config-1.1.7
Parsing documentation for glib2-3.0.8
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/glib2.bundle, skipping
Installing ri documentation for glib2-3.0.8
Parsing documentation for gobject-introspection-3.0.8
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/gobject_introspection.bundle, skipping
Installing ri documentation for gobject-introspection-3.0.8
Parsing documentation for ruby-vips8-0.1.0
Installing ri documentation for ruby-vips8-0.1.0
4 gems installed
john@katamata ~ $ irb
irb(main):001:0> require 'vips8'
=> true
irb(main):003:0> a = Vips::Image.new_from_file "/Users/john/pics/k2.jpg"
=> #<Vips::Image:0x7fa9aa92aee0 ptr=0x7fa9a8882010>
irb(main):004:0> ^D
```

You're right, you do need to set `PKG_CONFIG_PATH`. Mine is:

```
john@katamata ~ $ echo $PKG_CONFIG_PATH 
:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/opt/X11/lib/pkgconfig:/Users/john/vips/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
```

There are some notes about this on the "build on os x" page:

http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_OS_X

**Comment by jcupitt** [comment]
... the `rm -rf` at the beginning there was to blow away all my gems, in case it's not clear. I have `GEM_HOME` pointing to that directory.

**Comment by PaulHowson** [comment]
Thanks John. Will look at it again at the next opportunity.

**Comment by Nakilon** [comment]
I'm not sure that `brew install ruby` is a nice idea at all. The one should use `rbenv` (or `rvm`) if he wants non-default Ruby.

**Comment by jcupitt** [comment]
Good to know @Nakilon, thanks. I usually use the brew python, but I've never tried their ruby before.

**Comment by sandstrom** [comment]
@jcupitt @PaulHowson can this issue be closed?

**Comment by PaulHowson** [comment]
I opened the issue, but ended up putting it in the too hard basket for another day. Reverted to an earlier Ruby install. So, yes I will close it for now.
